name: CI -> Deploy to My website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build node app
      - uses: actions/setup-node@v4
      # Here is the deployment action
        with:
          node-version: 18
      - run: npm build
      - name: Upload from dist via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: app/dist
          remote_dir: app
